MyBlog/src/MyBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from MyBlog import settings
from MyBlog.views import LandingPageView

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
    path('admin/', admin.site.urls),
    path('blog/', include('Posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyBlog/src/Posts/urls.py
from django.urls import path
from Posts.views import BlogHomeView, BlogPostCreate, BlogPostUpdate, BlogPostDelete, BlogPostDetail
# from django.contrib.auth.decorators import login_required

app_name = "Posts"

urlpatterns = [
    path('', BlogHomeView.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name="edit"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
    path('<str:slug>/', BlogPostDetail.as_view(), name="post"),
    # path('create/', login_required(BlogPostCreate.as_view()), name="create"),
]

MyBlog/src/Posts/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.

# class Author(models.Model):
    # author = models.CharField(max_length=100)


User = get_user_model()


class BlogPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    content = models.TextField(blank=True, verbose_name="Contenu")
    created_on = models.DateField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    thumbnail = models.ImageField(blank=True, upload_to='MyBlog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        
    @property
    def author_or_default(self):
        return self.author.username if self.author else "Auteur anonyme"

    def get_absolute_url(self):
        return reverse('Posts:home')

MyBlog/src/MyBlog/views.py
from django.views.generic import TemplateView

class LandingPageView(TemplateView):
    template_name = "landing_page.html"

MyBlog/src/Posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from Posts.models import BlogPost
# Create your views here.


class BlogHomeView(ListView):
    model = BlogPost
    # template_name = ""
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "Posts/blogpost_create.html"
    fields = ["title", "content", "created_on", ]


@method_decorator(login_required, name='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "Posts/blogpost_edit.html"
    fields = ["title", "content", "published"]


@method_decorator(login_required, name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    # template_name = "Posts/blogpost_delete.html"
    success_url = reverse_lazy("Posts:home")
    context_object_name = "post"


class BlogPostDetail(DetailView):
    model = BlogPost
    # template_name = "Posts/blogpost_detail.html"
    context_object_name = "post"

MyBlog/src/Posts/templates/Posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer l'article ?</title>
{% endblock %}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer l'article {{ post }} ?</p>
        <input type="submit" value="Oui, supprimer" class="btn btn-delete">
    </form>

{% endblock %}

MyBlog/src/Posts/templates/Posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Ajouter un article</title>
{% endblock %}


{% block content %}

    <h1>Ajouter un article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Créer" class="btn btn-submit">
    </form>

{% endblock %}

MyBlog/src/Posts/templates/Posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ post.title }}</title>
{% endblock %}


{% block content %}

  <article class="post-detail">
    <h1>{{ post.title }}</h1>
    <img src="{{ post.thumbnail.url }}" alt="thumbnail">
    <h5>Publié par: <i>{{ post.author_or_default }}</i> le {{ post.created_on }}</h5>
    <p>{{ post.content|linebreaks|safe }}</p>
  </article>

  {% if request.user.is_authenticated %}
  <a href="{% url 'Posts:edit' slug=post.slug %}">Modifier</a>
  <a href="{% url 'Posts:delete' slug=post.slug %}">Supprimer</a>
  {% endif %}


{% endblock %}

MyBlog/src/Posts/templates/Posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Modifier l'article</title>
{% endblock %}


{% block content %}

    <h1>Modifier l'article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Modifier" class="btn btn-submit">
    </form>

{% endblock %}

MyBlog/src/Posts/templates/Posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
<title>Bienvenue sur MyBlog</title>
{% endblock title %}

{% block content %}
<h1>MyBlog</h1>
{% for post in posts %}
<article>
    <!--                <h2><a href="{% url 'Posts:post' slug=post.slug %}">{{ post.title }}</a></h2>-->

    <div class="post-title">
        <h2>{{ post.title }}</h2>

        {% if request.user.is_authenticated %}
        <div>
            <a href="{% url 'Posts:edit' slug=post.slug %}">Modifier</a>
            <a href="{% url 'Posts:delete' slug=post.slug %}">Supprimer</a>
            {% endif %}
        </div>
    </div>

    <h5 class="post-author">Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }} </h5>
    <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>

    <form action="{% url 'Posts:post' slug=post.slug %}">
        <button class="btn btn-submit">Lire l'article</button>
    </form>
</article>
{% endfor %}

{% endblock content %}

MyBlog/src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block title %}
    <title>Accueil de MyBlog</title>
    {% endblock %}

</head>

<body>

    <nav>
        <a href="{% url 'Posts:home' %}">Accueil du site</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'Posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>

    <section id="blog">
    {% block content %}{% endblock %}
    </section>

</body>

</html>

MyBlog/src/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Lading Page</title>
{% endblock %}

{% block content %}
    <h1>Welcome to MyBlog</h1>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'Posts:home' %}">MyBlog Index</a>
{% endblock %}